homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('experiences/', views.experiences, name='experiences'),
    path('skills/', views.skills, name='skills'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('isijadwal/', views.isijadwal, name='isijadwal'),
    path('contact/', views.contact, name='contact'),
    path('delete/<int:delete_id>', views.delete, name = 'delete'),
    # dilanjutkan ...
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
import datetime

# Create your models here.

class Jadwal(models.Model):
    kegiatan = models.CharField(max_length=100)
    kategori = models.CharField(max_length=100)
    tempat = models.CharField(max_length=100)
    tanggal = models.DateField()
    waktu = models.TimeField(default=datetime.time(12,00))

    def __str__(self):
        return "{}.{}".format(self.id,self.kategori)

homepage/forms.py
from django import forms

from .models import Jadwal

class JadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = {
            'kegiatan',
            'kategori',
            'tempat',
            'tanggal',
            'waktu',
        }


        widgets = {
            'kegiatan' : forms.TextInput(
                attrs={
                    'class' : 'form-control',

                }
            ),

            'kategori' : forms.TextInput(
                attrs={
                    'class' : 'form-control',
                }
            ),

            'tempat' : forms.TextInput(
                attrs={
                    'class' : 'form-control',
                }
            ),

            'tanggal' : forms.DateInput(
                attrs={
                    'class' : 'form-control',
                    'placeholder' :'YYYY-MM-DD'
                }

            ),

            'waktu' : forms.TimeInput(
                attrs={
                    'class' : 'form-control',
                }

            ),
        }

homepage/views.py
from django.shortcuts import render,redirect

# Create your views here.
from .models import Jadwal
from .forms import JadwalForm

def home(request):
    return render(request, 'Home.html')

def profile(request):
    return render(request, 'Profile.html')

def experiences(request):
    return render(request, 'Experiences.html')

def skills(request):
    return render(request, 'Skills.html')

def jadwal(request):
    list_jadwal = Jadwal.objects.all()

    context = {
        'list_jadwal':list_jadwal,
    }
    return render(request, 'Jadwal.html',context)

def isijadwal(request):
    form_jadwal = JadwalForm(request.POST or None)

    if request.method == 'POST':
        if form_jadwal.is_valid():
            form_jadwal.save()

        return redirect('homepage:jadwal')

    context = {
        'form_jadwal':form_jadwal,
    }

    return render(request, 'IsiJadwal.html',context)

def contact(request):
    return render(request, 'Contact.html')

def base(request):
    return render(request, 'Base.html')

def delete(request,delete_id):
    Jadwal.objects.filter(id=delete_id).delete()
    return redirect('homepage:jadwal')

homepage/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/MyStyle.css' %}">
</head>
<div id="menu">
  <nav>
    <ul class="main_menu">
      <li><a href="{% url 'homepage:home' %}" class="nav-link">home</a></li>
      <li><a href="{% url 'homepage:profile' %}" class="nav-link">profile</a></li>
      <li><a href="{% url 'homepage:experiences' %}" class="nav-link">experiences</a></li>
      <li><a href="{% url 'homepage:skills' %}" class="nav-link">skills</a></li>
      <li><a href="{% url 'homepage:jadwal' %}" class="nav-link">schedule</a></li>
      <li><a href="{% url 'homepage:contact' %}" class="nav-link">contact</a></li>
    </ul>
  <nav>
</div>

<body>
  {% block content %}
  {% endblock %}
</body>

<div>
  <p class="footer">Made with Luv by Arkansas~</p>
</div>

homepage/templates/Contact.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
<div id="content" class="container">
  <div class="row">
    <div class="col  text-center">
      <h1>You can hit me on</h1>
    </div>
  </div>
  <div id="contact" class="row">
    <div class="col">
        <a href="https://www.linkedin.com/in/arkan-sabilla-asfa-bab201113/">
        <img src="{% static 'images/031-linkedin.png' %}"  width="100px" height="100px">
    </div>
    <div class="col">
      <a href="https://open.spotify.com/user/21qslemime5anjp43hkrp2scy">
      <img src="{% static 'images/019-spotify.png' %}"  width="100px" height="100px">
    </div>
    <div class="col">
      <a href="https://steamcommunity.com/id/arkansas0315/">
      <img src="{% static 'images/steam-logo.png' %}"  width="100px" height="100px">
    </div>
  </div>
  <div id="contact" class="row">
    <div class="col">
        <a href="https://web.facebook.com/arkan.asfa">
        <img src="{% static 'images/045-facebook.png' %}"  width="100px" height="100px">
    </div>
    <div class="col">
      <a href="https://twitter.com/arkansasfa">
      <img src="{% static 'images/013-twitter-1.png' %}"  width="100px" height="100px">
    </div>
    <div class="col">
      <a href="https://www.instagram.com/arkan_sas/">
      <img src="{% static 'images/034-instagram.png' %}"  width="100px" height="100px">
    </div>
  </div>
</div>
{% endblock %}

homepage/templates/Experiences.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
  <div class="row">
      <div class="col">
        <h1>
          Education
       </h1>
        <p>
          <li>SDIT Al-Manar           2004-2010</li>
          <li>SMPN 1 Bekasi           2010-2013</li>
          <li>SMAN 1 Bekasi           2013-2016</li>
          <li>Universitas Indonesia   2016-Now</li>
       </p>
     </div>

     <div class="col">
       <h1>
         Organization
      </h1>
       <p>
         <li>Chairman of Cyber Community SMAN 1 Bekasi 2014-2015</li>
         <li>Staff of BEM Fasilkom UI 2019</li>
      </p>
    </div>
    <div class="col">
      <h1>
        Volunteer
     </h1>
      <p>
        <li>Staff of Cyber Competition SMAN 1 Bekasi</li>
        <li>Staff of PEMIRA IKM Fasilkom UI 2018</li>
        <li>Liaison Officer of Wisuda Ganjil</li>
        <li>Liaison Officer of Wisuda Genap</li>
        <li>Vice Project Officer of PEMIRA IKM Fasilkom UI 2019</li>
     </p>
   </div>
</div>
{% endblock %}

homepage/templates/Home.html
{% extends "Base.html" %}

{% block content %}
  <div id="content" class="container">
    <div class="row">
      <div class="col  text-center">
        <h1>Hello, this is <mark>Arkansas</mark> Website</h1>
      </div>
    </div>
  </div>
{% endblock %}

homepage/templates/IsiJadwal.html
{% extends "Base.html" %}

{% block content %}
<form method="POST">
  {% csrf_token %}

  <div id='isiJadwal'>
      <form method='POST'>

          {% csrf_token %}

          {{ form_jadwal.non_field_errors }}

          <div class="form-group">
              {{form_jadwal.kegiatan.errors }}
              <p style="text-align: left">{{form_jadwal.kegiatan.label}} </p>
              <div>{{form_jadwal.kegiatan}}</div>
          </div>

          <div class="form-group">
              {{form_jadwal.kategori.errors }}
              <p style="text-align: left">{{form_jadwal.kategori.label}} </p>
              <div>{{form_jadwal.kategori}}</div>
          </div>

          <div class="form-group">
              {{form_jadwal.tempat.errors }}
              <p style="text-align: left">{{form_jadwal.tempat.label}} </p>
              <div>{{form_jadwal.tempat}}</div>
          </div>

          <div class="form-group">
              {{form_jadwal.tanggal.errors }}
              <p style="text-align: left">{{form_jadwal.tanggal.label}} </p>
              <div>{{form_jadwal.tanggal}}</div>
          </div>

          <div class="form-group">
              {{form_jadwal.waktu.errors }}
              <p style="text-align: left">{{form_jadwal.waktu.label}} </p>
              <div>{{form_jadwal.waktu}}</div>
          </div>


          <button class="btn btn-light" type="submit">Daftarkan</button>
      </form>
</div>


{% endblock %}

homepage/templates/Jadwal.html
{% extends "Base.html" %}

{% block content %}
<table class="table">
  <thead>
    <tr class="table-light">
      <th scope="col">No.</th>
      <th scope="col">Kegiatan</th>
      <th scope="col">Kategori</th>
      <th scope="col">Tempat</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Waktu</th>
      <th scope="col">Hapus</th>
    </tr>
  </thead>
  <tbody>
    {% for list in list_jadwal %}
    <tr class="table-light">
      <td>{{ forloop.counter }}</td>
      <td>{{list.kegiatan}}</td>
      <td>{{list.kategori}}</td>
      <td>{{list.tempat}}</td>
      <td>{{list.tanggal}}</td>
      <td>{{list.waktu}}</td>
      <td><a class='btn btn-danger' href="{% url 'homepage:delete' delete_id=list.id %}">Delete</a>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div id="wrapper">
  <a href="{% url 'homepage:isijadwal' %}" class="btn btn-light" role="button">Buat Jadwal</a>
</div>
{% endblock %}

homepage/templates/Profile.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
  <div id="content" class="container">
    <div class="row">
      <div class="col">
        <img src="{% static 'images/apaini.jpg' %}" width="350px" height="350px">
      </div>
      <div class="col">
        <p>
          Name: Arkan Sabilla Asfa
        </p>
        <p>
          Nickame: Arkansas
        </p>
        <p>
          Birth date: 15 March 1998
        </p>
        <p>
          Major: Information Systems, Faculty of Computer Science, Universitas Indonesia
        </p>
        <p>
          Hobbies:
          <li>Reading</li>
          <li>Writing</li>
          <li>Sleeping</li>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        <h1>
          About Me
       </h1>
     </div>
   </div>
   <div class="row">
     <div class="col text-justify">
       <p>
         A young man with a dream as high as blue sky. Have high interest in social politic, philosophy, and computer. Not so genius, but always hardworking when doing something.
         Have cheerful personality and always trying to share happiness to other people. Love to learn something new especially things that related to my interests.
         Hate defeat and always blame myself if do something lower than my expectations.
      </p>
    </div>
  </div>
  </div>
{% endblock %}

homepage/templates/Skills.html
{% extends "Base.html" %}
{% load static %}

{% block content %}
  <div id="content" class="container">
    <div class="row">
      <div class="col">
        <h1>
          My Skills:
        </h1>
        <p>
          <li>Fiction Writing</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:20%;">
                20%
            </div>
          </div>
        </p>
        <p>
          <li>English</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:10%;">
                  10%
            </div>
          </div>
        </p>
        <p>
          <li>Japanese</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:10%;">
                  10%
            </div>
          </div>
        </p>
        <p>
          <li>Indonesian</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:30%;">
                  30%
            </div>
          </div>
        </p>
        <p>
          <li>Python</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:5%;">
                  5%
            </div>
          </div>
        </p>
        <p>
          <li>Java</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:5%;">
                  5%
            </div>
          </div>
        </p>
        <p>
          <li>Adobe Photoshop</li>
          <div class="progress">
            <div class="progress-bar progress-bar-striped
                    progress-bar-animated" style="width:10%;">
                  10%
            </div>
          </div>
        </p>
      </div>
    </div>
  </div>
{% endblock %}